import React, { useState, useRef, useEffect } from 'react'
import Head from 'next/head'
import styled from 'styled-components'
import logo from '../images/logo.svg'
import Toolbar from 'osmium-toolbar'

export default function Home() {

  const [isPrimary, setIsPrimary] = useState(true);
  const [pageLoaded, setPageLoaded] = useState(false)

  useEffect(() => {
    if(logo){
      setPageLoaded(true)
    }
  }, [logo])

  const scrolledTop = useRef(true);
  const scrolling = (scrollTop) => {
    if (scrollTop === 0) {
      if (!scrolledTop.current) {
        scrolledTop.current = true;
        setIsPrimary(true);
      }
    } else {
      if (scrolledTop.current) {
        scrolledTop.current = false;
        setIsPrimary(false);
      }
    }
  };

  return (
    <div>
      <Head>
        <title>Osmium - Inspections done right.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Container onScroll={(e) => scrolling(e.target.scrollTop)}>
        {
          pageLoaded ?
          <Toolbar isPrimary={isPrimary} logo={logo} text={""}></Toolbar>
          :null
        }
        <Content></Content>
      </Container>

      <footer>
       footer
      </footer>
    </div>
  )
}

const Container = styled.div`
  width: 100%;
  height: 100vh;
  background-color: #06419a;
  overflow: scroll;
`;

const Content = styled.div`
  height: 300vh;
`;

